### ISSUE TITLE
Install CMS API not working

### ISSUE THREAD

**Issue by find4u** [lemberg/connfa-integration-server#31]
Hi thanks for open sourcing this product I am having trouble getting the api to work
I can login to  console using admin.
however if I use http://localhost/connfa/api/v2 i get this error

{"message":"404 Not Found","status_code":404,"debug":{"line":161,"file":"D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":["#0 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(823): Illuminate\\Routing\\RouteCollection->match(Object(Dingo\\Api\\Http\\Request))","#1 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(691): Illuminate\\Routing\\Router->findRoute(Object(Dingo\\Api\\Http\\Request))","#2 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(675): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))","#3 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Laravel.php(82): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#4 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\dingo\\api\\src\\Routing\\Router.php(574): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v2')","#5 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(123): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#6 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#7 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(150): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#8 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#9 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#10 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#11 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#12 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#13 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(124): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#14 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(100): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#15 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))","#16 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#17 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#18 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#19 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#20 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#21 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#22 D:\\_dev\\PHPsrc\\integrationSrv\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(99): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))","#23 D:\\_dev\\PHPsrc\\integrationSrv\\public\\index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))","#24 {main}"]}}

I have tried using the index.php/api/v2 which gives the same error

I also tried http://localhost/connfa/east-emmie-2017/api/v2 which gives a 404

thanks a million for any help

Richard

**Comment by sanjayankur31** [comment]
Hi @find4u , 

I'm seeing the same thing. Were you able to solve this by any chance?

Cheers!
